name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      # Create a new Git release
      - name: Create Git Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*
          tag_name: v${{ github.ref }}
          name: Release v${{ github.ref }}
          body: |
            ####Changes in this release:
            - Add a detailed readme.
            - Provide doc strings where needed.
            - Provide defaults and overrides.
            - Implement smoothing to the mouse scroll.
          draft: false
          prerelease: false

      # Authenticate with npm
      # - name: Authenticate with npm
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc

      # # Publish the package to npm
      # - name: Publish to npm
      #   run: yarn publish
      #   if: github.ref == 'refs/heads/main'
