name: Build

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      # Authenticate with npm
      # - name: Authenticate with npm
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc

      # # Publish the package to npm
      # - name: Publish to npm
      #   run: yarn publish
      #   if: github.ref == 'refs/heads/main'
